import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Landing from "../comps/landing/Landing";
import Header from "../comps/header/Header";
//import Characters from "../comps/characters/Characters";
import Timeline from "../comps/timeline/Timeline";
import Footer from "../comps/footer/Footer";
import CharactersSlider from "../comps/charactersSlider/CharactersSlider";
import Team from "../comps/team/Team";
import Partners from "../comps/partners/Partners";
import GameInfo from "../comps/gameInfo/GameInfo";
import Tokemonics from "../comps/tokemonics/Tokemonics";

function Home({ buildTimestamp }) {
  console.log({ buildTimestamp });
  const [offsetY, setOffsetY] = useState(0);
  const handleScroll = () => setOffsetY(window.pageYOffset);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const [isPageBottom, setIsPageBottom] = useState(false);

  /* useEffect(() => {
    console.log("pageYOffset", window.pageYOffset);
    console.log("scrollY", window.scrollY);
    console.log("innerHeight", window.innerHeight);
    console.log();
    //////
  }, [offsetY]);*/

  return (
    <div className={styles.container}>
      {/** */}
      <Head>
        <title>Distopy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Landing offsetY={offsetY} />
        <GameInfo />
        <Tokemonics />
        <Partners />
        <Team />
        {/*<CharactersSlider />

        <Timeline offsetY={offsetY} />
  */}
      </div>
    </div>
  );
}

export const getStaticProps = () => {
  return {
    props: {
      buildTimestamp: Date.now(),
    },
  };
};

export default Home;
